# Generated by Django 3.1.1 on 2024-04-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20240409_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Comments',
            new_name='comment',
        ),
    ]
