# Generated by Django 3.1.1 on 2024-04-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20240409_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioprononciation',
            name='sentimental_score',
            field=models.FloatField(default=0),
        ),
    ]
